name = "istdochnichtwichtig"
license = "MIT"
licenselink = "https://github.com/colorchestra/smol/blob/master/LICENSE.md"
description = "Minimal Hugo theme without any tracking or external dependencies."
homepage = "https://www.gebiert.de"
tags = ["blog", "minimal", "dark mode", "simple", "clean", "light", "responsive", "fast", "no-js", "no-tracking", "privacy"]
features = ["blog", "privacy", "responsive", "fast"]
min_version = "0.20"

[author]
  name = "gebiert"
  homepage = "https://www.gebiert.de"
  
[original]
  name = "morph"
  homepage = "morph.sh"
  repo = "https://github.com/colorchestra/smol"
